export const ADD_TO_CART = "ADD_TO_CART";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_NEXT_ON_SCROLL = "LOAD_NEXT_ON_SCROLL";
export const INCREMENT_PAGENUMBER = "INCREMENT_PAGENUMBER";
